#!/usr/bin/env python
"""Generate semantic_models/unified/unified_model.yaml from the domain models.

The unified model is never hand-authored — it is always regenerated from
semantic_models/domains/*.yaml. This controls for "semantic model
authoring effort" as a hidden variable in the unified-vs-decomposed
comparison: if the unified model were separately hand-crafted, it could
end up better-written than the sum of the domain parts for reasons
unrelated to architecture.

Run:
    python scripts/generate_unified_model.py [--check]

--check exits non-zero if the checked-in unified_model.yaml would differ
from a fresh regeneration, without writing anything. Used by
tests/test_semantic_model_schema.py to enforce that nobody hand-edits the
generated file.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from semantic_models.schema import SemanticModel, load_semantic_model, validate_references  # noqa: E402

DOMAINS_DIR = REPO_ROOT / "semantic_models" / "domains"
UNIFIED_PATH = REPO_ROOT / "semantic_models" / "unified" / "unified_model.yaml"

GENERATED_HEADER = (
    "# GENERATED FILE — do not hand-edit.\n"
    "# Produced by scripts/generate_unified_model.py from semantic_models/domains/*.yaml.\n"
    "# Re-run that script after changing any domain model, and commit the result.\n\n"
)


def load_domain_models() -> list[SemanticModel]:
    paths = sorted(DOMAINS_DIR.glob("*.yaml"))
    if not paths:
        raise SystemExit(f"No domain models found in {DOMAINS_DIR}")
    return [load_semantic_model(p) for p in paths]


def build_unified_model(domain_models: list[SemanticModel]) -> dict:
    entities: list[dict] = []
    relationships: list[dict] = []
    dimensions: list[dict] = []
    metrics: list[dict] = []

    seen_entity_names: dict[str, str] = {}  # entity name -> owning domain
    for m in domain_models:
        for e in m.entities:
            if e.name in seen_entity_names:
                raise SystemExit(
                    f"Entity name collision: {e.name!r} is defined in both "
                    f"{seen_entity_names[e.name]!r} and {m.domain!r}. Entity names "
                    "must be unique across all domain models to merge unambiguously "
                    "into the unified model."
                )
            seen_entity_names[e.name] = m.domain
            entities.append(e.model_dump(by_alias=True, exclude_none=True))

        for r in m.relationships:
            relationships.append(r.model_dump(by_alias=True, exclude_none=True))

        for d in m.dimensions:
            dimensions.append(d.model_dump(by_alias=True, exclude_none=True))

        for met in m.metrics:
            metrics.append(met.model_dump(by_alias=True, exclude_none=True))

    # This is the architectural crux of "unified": cross-domain foreign keys
    # become native, first-class relationships, visible to the agent
    # alongside every within-domain relationship — nothing about a
    # cross-domain join looks different from a same-domain join once merged.
    for m in domain_models:
        for cdk in m.cross_domain_keys:
            relationships.append(
                {
                    "from": f"{cdk.entity}.{cdk.join_key}",
                    "to": cdk.references.split(".", 1)[1],  # drop the "<domain>." prefix
                    "type": "many_to_one",
                }
            )

    return {
        "domain": "unified",
        "description": (
            "Unified semantic model spanning all domains: "
            + ", ".join(m.domain for m in domain_models)
            + ". Generated by concatenating the domain models and promoting each "
            "cross_domain_key to a first-class relationship."
        ),
        "entities": entities,
        "relationships": relationships,
        "dimensions": dimensions,
        "metrics": metrics,
        "cross_domain_keys": [],
    }


def main() -> None:
    check_only = "--check" in sys.argv

    domain_models = load_domain_models()

    # Validate each domain model individually before merging.
    all_errors: list[str] = []
    for m in domain_models:
        all_errors.extend(validate_references(m))
    if all_errors:
        for err in all_errors:
            print(f"ERROR: {err}", file=sys.stderr)
        raise SystemExit(1)

    unified_dict = build_unified_model(domain_models)

    # Round-trip through the schema to confirm the generated file is itself valid.
    SemanticModel.model_validate(unified_dict)

    new_content = GENERATED_HEADER + yaml.dump(
        unified_dict, sort_keys=False, default_flow_style=False
    )

    if check_only:
        current_content = UNIFIED_PATH.read_text() if UNIFIED_PATH.exists() else ""
        if current_content != new_content:
            print(
                f"{UNIFIED_PATH} is out of date with the domain models. "
                "Run `python scripts/generate_unified_model.py` and commit the result.",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print("unified_model.yaml is up to date.")
        return

    UNIFIED_PATH.parent.mkdir(parents=True, exist_ok=True)
    UNIFIED_PATH.write_text(new_content)
    print(f"Wrote {UNIFIED_PATH} from {len(domain_models)} domain models.")


if __name__ == "__main__":
    main()
